apiVersion: apps/v1
kind: Deployment # Kubernetes resource kind we are creating
metadata:
  name: jenkins-test-k8s
spec:
  selector:
    matchLabels:
      app: jenkins-test-k8s
  replicas: 2 # Number of replicas that will be created for this deployment
  template:
    metadata:
      labels:
        app: jenkins-test-k8s
    spec:
      containers:
        - name: jenkins-test-k8s
          image: sachinbagla/jenkin-test:latest
          # Image that will be used to containers in the cluster
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
# The port that the container is running on in the cluster
---
apiVersion: v1 # Kubernetes API version
kind: Service # Kubernetes resource kind we are creating
metadata: # Metadata of the resource kind we are creating
  name: jenkins-test-k8s-svc
spec:
  selector:
    app: jenkins-test-k8s
  ports:
    - protocol: "TCP"
      port: 8080 # The port that the service is running on in the cluster
      targetPort: 8080 # The port exposed by the service
  type: NodePort # type of the service.
